# Generated by Django 3.2.5 on 2021-07-27 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='isOrder',
            field=models.BooleanField(default=False),
        ),
    ]
